export const GET_ERRORS = 'GET_ERRORS';
export const GET_RESPONSE_TYPE = 'GET_RESPONSE_TYPE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_REQUEST_INFO = 'GET_REQUEST_INFO';
export const GET_RESPONSE_DATA = 'GET_RESPONSE_DATA';